"""Init

Revision ID: 2c89296bc6fd
Revises: 
Create Date: 2024-10-13 00:39:54.864794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c89296bc6fd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('amount', sa.DECIMAL(), nullable=True),
    sa.Column('label', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('COMPLETED', 'UNCOMPLETED', name='paymentstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_history_label'), 'payments_history', ['label'], unique=False)
    op.create_index(op.f('ix_payments_history_user_id'), 'payments_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_history_user_id'), table_name='payments_history')
    op.drop_index(op.f('ix_payments_history_label'), table_name='payments_history')
    op.drop_table('payments_history')
    # ### end Alembic commands ###
